FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy application files
COPY . /app

# Copy wait-for-it.sh script
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Install dependencies
RUN pip install --no-cache-dir kafka-python

# Set the default command to run wait-for-it.sh and then the consumer
CMD ["/wait-for-it.sh", "kafka:9092", "--", "python", "consumer.py"]
