version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8000:8000"

  post-service:
    build:
      context: ./post-service
    ports:
      - "8001:8000"

  admin-service:
    build:
      context: ./admin-service
    ports:
      - "8002:8000"
