version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8000:8000"
    env_file:
      - ./user-service/.env
    depends_on:
      - mysql_db
      - neo4j_db
    networks:
      - thread-hive-network

  post-service:
    build:
      context: ./post-service
    ports:
      - "8001:8000"
    env_file:
      - ./post-service/.env
    depends_on:
      - mongodb
    networks:
      - thread-hive-network

  admin-service:
    build:
      context: ./admin-service
    ports:
      - "8002:8000"
    env_file:
      - ./admin-service/.env
    depends_on:
      - admin_mysql_db
      - user-service
      - post-service
      - kafka-consumer
    networks:
      - thread-hive-network

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - ./user-service/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-mysql:/docker-entrypoint-initdb.d
    networks:
      - thread-hive-network

  admin_mysql_db:
    image: mysql:8.0
    container_name: admin_mysql_db
    restart: always
    env_file:
      - ./admin-service/.env
    ports:
      - "3308:3306"
    volumes:
      - admin_mysql_data:/var/lib/mysql
      - ./init-admin-mysql:/docker-entrypoint-initdb.d
    networks:
      - thread-hive-network

  neo4j_db:
    image: neo4j:5.8.0
    container_name: neo4j_db
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - ./user-service/.env
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - thread-hive-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    env_file:
      - ./post-service/.env
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongodb:/docker-entrypoint-initdb.d
    networks:
      - thread-hive-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - thread-hive-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - thread-hive-network

  kafka-consumer:
    build:
      context: ./kafka-consumer
    depends_on:
      - kafka
    networks:
      - thread-hive-network
    environment:
      KAFKA_BROKER: kafka:9092  # Kafka broker address
      TOPIC_NAME: user_signup  # Replace with your topic name

volumes:
  mysql_data:
  admin_mysql_data:
  neo4j_data:
  neo4j_logs:
  mongodb_data:

networks:
  thread-hive-network:
