// constants/posts.ts

export const posts = [
  {
    id: 1,
    username: "Elon Musk",
    avatar: "/images/avatar/elon_musk.jpg",
    content: "Trump will win! #Election2024 #Trump2024 #MAGA #KAG #TrumpWon",
    timestamp: "2024-11-19T12:00:00Z",
    comments: 10,
    retweets: 5,
    likes: 20,
    images: ["/images/post/elon_musk/1.jpg"],
  },
  {
    id: 2,
    username: "Elon Musk",
    avatar: "/images/avatar/elon_musk.jpg",
    content: "Great things are coming! #SpaceX #Tesla #ElonMusk #Mars #Moon",
    timestamp: "2024-11-19T11:30:00Z",
    comments: 5,
    retweets: 3,
    likes: 15,
    images: ["/images/post/elon_musk/2.jpg"],
  },
  {
    id: 3,
    username: "Elon Musk",
    avatar: "/images/avatar/elon_musk.jpg",
    content: "Hi I'd like to talk about the project today... ",
    timestamp: "2024-11-18T10:45:00Z",
    comments: 5,
    retweets: 3,
    likes: 15,
    images: ["/images/post/elon_musk/3.jpg"],
  },
  {
    id: 4,
    username: "Post Malone",
    avatar: "images/avatar/post_malone.jpg",
    content:
      "Hello It's Anthony from SJSU! And these are static values. All we need to do is to fetch the data from the backend and display it here.",
    timestamp: "2024-11-19T12:00:00Z",
    comments: 10,
    retweets: 5,
    likes: 20,
    images: ["/images/post/post_malone/1.jpg"],
  },
  {
    id: 5,
    username: "Post Malone",
    avatar: "images/avatar/post_malone.jpg",
    content: "Hello It's Nisarg from SJSU as well. Have a great day!",
    timestamp: "2024-11-19T11:30:00Z",
    comments: 5,
    retweets: 3,
    likes: 15,
    images: ["/images/post/post_malone/2.jpg"],
  },
  {
    id: 6,
    username: "Post Malone",
    avatar: "images/avatar/post_malone.jpg",
    content: "Hi I'd like to talk about the project today... ",
    timestamp: "2024-11-18T10:45:00Z",
    comments: 5,
    retweets: 3,
    likes: 15,
    images: ["/images/post/post_malone/3.jpg"],
  },
];
